requirements.txt: Upgrade Markdown
ERROR: Cannot install Markdown==3.2.1 and mkdocs==1.6.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Markdown==3.2.1
    mkdocs 1.6.1 depends on markdown>=3.3.6